### ISSUE TITLE
Messy license notice in some instances

### ISSUE THREAD

**Issue by Pogodaanton** [TobyAndToby/generate-license-file#1]
**What happens currently?**
The CLI regards the package's README as the license file in some instances. Due to this the generated file contains the wrong license notice for that project.

![Example image](https://user-images.githubusercontent.com/8974778/87232600-60007000-c3c0-11ea-93c3-5a00a89bcd9b.png)

**What should happen?**
Since every package.json needs to have a license field, using that as a fallback is possible. However, the CLI could also retrieve generic licenses through [some API of sorts](https://developer.github.com/v3/licenses/#get-all-commonly-used-licenses).

**Comment by tobysmith568** [comment]
Reopening

**Comment by tobybessant** [comment]
Hey @PixelPage-YT,

Thanks for your comment. Now that we've released version 2, addressing this is definitely on our radar.

We've taken a look at a fix and a proper solution is not a small amount of work, and we're surprised to hear this is a major blocker for you. As the code currently sits, it errs on the side of caution - potentially containing more (superfluous) content rather than accidentally missing something critical.

Can you go into more details as to why this issue prevents you from using generate-license-file?

**Comment by PixelPage-YT** [comment]
Thanks for the answer! For me, I like it simple. That's why I chose generate-license-file, but the fact that I have to scroll through the whole file (4000 lines) and remove unnecessary things is just not the goal of the project.

**Comment by wcroteau** [comment]
> We've taken a look at a fix and a proper solution is not a small amount of work, and we're surprised to hear this is a major blocker for you. As the code currently sits, it errs on the side of caution - potentially containing more (superfluous) content rather than accidentally missing something critical.
> 
> Can you go into more details as to why this issue prevents you from using generate-license-file?

I'm having this exact problem and I can give you a great reason:  In my case it is indeed "missing something critical" - with my particular 3p lib it is NOT including the license and instead only using the readme which is MISSING key license information.

So this is not a mere nuisance but rather missing some key content.

For reference I'm experiencing this issue with the package: ngx-spinner@15.0.1

**Comment by tobysmith568** [comment]
Hey @wcroteau

Thanks for taking the time to contribute to this discussion however in the case of ngx-spinner it is the library itself that is "missing something critical", not generate-license-file.

I've raised Napster2210/ngx-spinner#250 over on their repository and hopefully they respond promptly so that your issue can be solved.

**Comment by wcroteau** [comment]
Aha!  Thanks for taking the time to look into it.  I admit to having inspected the git repo instead of the deployed package.

**Comment by rodri042** [comment]
@tobysmith568 Is there a way to disable this behavior? I would prefer not to include anything in case one library doesn't include a license (vs including the whole README.md, which could increase the resulting file size really fast).

**Comment by tobysmith568** [comment]
Hey @rodri042. Including an option to alter this behaviour is an interesting point. I think we need to flesh out how it would alter the behaviour of the tool should we go down that route.

When said flag is given, what would be your suggestion for how the CLI should behave when it finds a package that has no dedicated license file? I'd suggest it could/should not continue on it's happy-path because you're then no longer adhering to the constraints of your dependency's licenses to the best of your abilities.

@tobybessant and I have spoken in the past about reducing when the readme is included but we've never found a clear divide between keeping the output concise and making sure to include a license at all costs where possible. (It is after all a hard requirement to include licenses when necessary).

Out of interest, do you have a reason why you'd prefer the resulting file to be particularly small?

**Comment by wcroteau** [comment]
I have some ideas but you're not going to like them... ;-)

I'm of at least two minds on this issue:
1. being sure to include a license at all costs where possible is a GREAT fallback position
2. the file can/does include completely useless information even in that fallback case depending completely on the 3rd party's (mis)configuration

Let's be honest, I don't expect anyone to read that file - it's purely intended for legal compliance - unless the lawyers get involved, in which case you'd better hope you've done it right.

Due to that I feel that I must review it from time-to-time and at least initially make sure it's working correctly.  My project is not particularly large yet my generated license file is over 16,000 lines - that's a lot to read/digest/tweek by hand for EVERY build.

The problem as you've pointed out is that some 3rd party lib authors have missing (or incorrect) license files which really messes things up forcing me to "do something about it".

Ironically, in many of the cases where the readme file gets included it's often missing the important license text which is supposed to be there anyways and simply says something like "LICENSE MIT" - which is strictly not sufficient.

Therefore it could be argued that my use of an automated tool is not sufficient to prove that I've made a "best effort" to include license files even if the author made this mistake - it's probably in my best interest to actually go and find/reproduce the missing text in my generated file.

This all becomes problematic when my file is over 16,000 lines and then I have to manually fix dozens of entries by sloppy 3rd parties...  UGH!

So enter my suggestions:

1. Make the "include readme when license doesn't exist" an option
2. WARN me that this has happened (a nice list with the libs in question would be great)
3. Allow me to incorporate a PERSISTENT manual injection in the file.  For example if we could incorporate some kind of #KEEP / #ENDKEEP pair in my file THEN I could manually "fix" the file ONCE and then set the option to "don't include readme" in favour of this keep comment which would contain the proper license file that I've sussed out (at least until I change versions)

I realize that this is becoming a lot of work because now you'll need to first parse the existing output file and cache the KEEP blocks BUT I would suggest that this would make the tool ultimately the most useful.

**Comment by wcroteau** [comment]
Another idea:  Can you instead pull the "license" entry out of the package.json?  In most cases that would likely be more helpful than the readme file...

**Comment by Pogodaanton** [comment]
> Another idea: Can you instead pull the "license" entry out of the package.json? In most cases that would likely be more helpful than the readme file...

Many licenses require to include a (full) copy of the original license (e.g. MIT), so only stating which type of license it is does not cover you legally, hence the README inclusion.

**Comment by tobysmith568** [comment]
Hey all,

Firstly - we want to say a huge thanks for the extensive input and discussion on this thread. It's been massively useful in giving us some concrete use cases as discussion points for the next version of the package.

I'm pleased to announce that we released a new beta version last week ([`3.0.0-beta.1`](https://www.npmjs.com/package/generate-license-file/v/3.0.0-beta.1)) that introduces some changes that will hopefully address your issues.

This takes the form of two key changes:

- We've rewritten the logic at the core of the package which now gives us finer control over what license text is used for a given package, and have set it to use the package.json `"license"` value as the final fallback (the README is no longer considered).

- We've added support for a configuration file, that allows users to:
  * arbitrarily append content to the generated file
  * remove packages from the output
  * replace a package's license content.
 
  You can see the API for this in the [README.md](https://github.com/TobyAndToby/generate-license-file?tab=readme-ov-file#advanced-configuration-beta).

If you're interested in doing so, we encourage you all to install this beta version and give us your feedback here. If we don't hear any concerns in this thread in the next 14 days then we'll go ahead and release version 3.0.0. Obviously you can raise new issues after that point and we'll do our best to address them.

```
npm i generate-license-file@3.0.0-beta.1
```

Note that: a side effect of us rewriting our core logic is that licenses are now ordered differently in the output (they're now alphabetical). This means that it'll be slightly trickier for you to perform a quick diff between the old and new versions of the output. We're sorry about this, but we think it's a worthwhile trade-off for the benefits of the new implementation. If you pick out some key packages and compare the output for those then you'll be able to see the differences.

<hr />

### Individual responses

@Pogodaanton
> Since every package.json needs to have a license field, using that as a fallback is possible.

This is now the case.

<hr />

@Pogodaanton
> However, the CLI could also retrieve generic licenses through some API of sorts.

We have chosen to not take this route as we wanted to avoid having a dependency on the internet at runtime.

<hr />

@PixelPage-YT
> the fact that I have to scroll through the whole file (4000 lines) and remove unnecessary things is just not the goal of the project.

You should now find that don't need to do this. You can now used the advanced configuration options that we expose via the config file to automatically configure the handling of problematic packages should you not like our new sensible defaults.

<hr />

@rodri042
> I would prefer not to include anything in case one library doesn't include a license.

We strongly suggest you don't exclude a package based solely on the fact that they’ve not included a license - however you can now do that if you wish using the new `exclude` option in the config file. The new default behaviour for a package that doesn't include a license is to use the package.json `"license"` value as the final fallback - we hope this will be acceptable for you.

<hr />

@wcroteau
> in many of the cases where the readme file gets included [...] it simply says something like "LICENSE MIT" - which is strictly not sufficient.

@Pogodaanton
> Many licenses require you to include a (full) copy of the original license (e.g. MIT), so only stating which type of license it is does not cover you legally, hence the README inclusion.

It's certainly true that many licenses explicitly require you to include a copy of the license - and this is mostly why this project even exists. However, we're not sure what we can do other than blindly include the README, or fall back to the `"license"` key in the package.json. As you know we initially went with the former and we're now going with the latter. This means while our previous approach was along the lines of "we can't find a license, let's hope there's one in the README", it's now "we can't find a license but we do at least know it's name". Neither approach is perfect but we hope you'll agree that the sentiment of the new approach is better.

Perhaps down the road, if there's demand for it, we'll introduce something akin to a `--strict` flag that will make the CLI fall over with a graceful error message if specifically license _content_ cannot be found either in the package or via the new `replace` option in the config file. Though we fear this option may be unusable simply due to how many packages out there don't include a license. Maybe you'd prefer this though, please let us know.

<hr />

@Pogodaanton
> Telling the user which projects the script pulled the README from is a good first step at easing the manual review process.

It should now be easy to spot packages like this as they'll be in the output with only an SPDX license identifier as their content. Perhaps, if there's desire for it, we could better identify these licenses either with a new command or the hypothetical `--strict` flag mentioned above. Again, after the release of `3.0.0` lets re-discuss this in a new issue if you'd like.

<hr />

@Pogodaanton
> the user could also create a sub-directory in which they store all manually compiled licenses, such that the script can pull them from there.

This can now be achieved with our new `replace` config option, should you wish to.

**Comment by tobysmith568** [comment]
Hey all, there were a couple of speedbumps on our end but today we've released version 3.0.0.

As mentioned above, we believe it strikes a good balance between most of your suggestions and hopefully everyone is now either happy with the new output or can address their issues/concerns using our new config options.

Please feel free to raise any new issues if you've got any new thoughts or concerns, thanks!

**Comment by wcroteau** [comment]
Awesome!

Had to make *significant* use of the config file to get everything generating the way I want (but that's on the 3p devs not you) and thus far it's working fantastically.

Good job guys!
