### ISSUE TITLE
Only dependencies are considered, no devDependencies

### ISSUE THREAD

**Issue by eichiflSICKAG** [TobyAndToby/generate-license-file#226]
Is it right, that this tool only generates disclaimers for `dependencies`, but not `devDependencies` or am I missing something?
Would be nice, to have an option for that!

**Comment by tobysmith568** [comment]
Hey @eichiflSICKAG, yes it is correct that this tool only looks at your `dependencies`. This is because they are the only packages that you distribute. There's no need for you to distribute the licenses for your `devDependencies` because you don't distribute your `devDependencies` with your product.

However we'd be interested to hear if you have a specific use-case for needing your `devDependencies` to be included?

**Comment by eichiflSICKAG** [comment]
I wanted to use this plugin as replacement for yarn generate-disclaimer and this looks into devDependencies as well I think, no?

**Comment by tobysmith568** [comment]
Hey @eichiflSICKAG 

Yeah, this library/CLI is a great alternative to the `generate-disclaimer` Yarn sub-command. I've had a look and sure enough it seems that Yarn do include `devDependencies` in their output, however, we're not sure why they've done that.

Do you have a particular use-case where you require the `devDependencies` to be in the output? As I touched on above, if you're using this package and/or the Yarn `generate-disclaimer` sub-command to create a file that you ship with your product to ensure you adhere to your dependencies licenses, then it's fine to not include the `devDependencies` because you're not distributing them.

**Comment by tobysmith568** [comment]
Hey @eichiflSICKAG 

I'm going to close this issue for now because it's unclear to us if there's a valid use-case for wanting the `devDependencies` in the output.

If you (or anyone reading this) has a strong reason for why `devDependencies` should be included (or configurable), then please do reply below and we can re-open this.

Thanks :)
