### ISSUE TITLE
add a option to append with file name as package name

### ISSUE THREAD

**Issue by RichardLuo0** [TobyAndToby/generate-license-file#499]
**How are you using generate-license-file?**
- [ ] CLI
- [X] Library

When I use the `append` option to append a license, the license file's name is not being used. But licenses usually don't include the package name. I think maybe we can use the file name to indicate which package it is.
For example, I need to include a license from a package `test`. I can just get its license and rename it to `test.txt`, then generate-license-file will append the file with this content prepended:
```
The following package may be included in this product:
 - test
```

**Comment by tobysmith568** [comment]
Hey @RichardLuo0 ,

The current implementation of the append option allows for any arbitrary text to be added to the license file, not necessarily files that only contain licenses and no other text. As it has been suggested this feature would be a breaking change for all those that are using append to add text that might not strictly be only a license.

While there are multiple different ways it could be integrated without it having to be a breaking change, we'd first be interested to hear more about your situation and why you have licenses you'd like to include that aren't for packages in your node_moudules directory?

Thanks

**Comment by RichardLuo0** [comment]
> we'd first be interested to hear more about your situation and why you have licenses you'd like to include that aren't for packages in your node_moudules directory?
> 

For example, if I need to change some part of the package to meet my requirement, for convenience, I just clone its repo and do modification. Therefore I need to include their licenses to the merged license file.
A second case is if I copy part of a project(not a package that meant to be used by other projects)'s source code. I need to bring their license too.

**Comment by tobysmith568** [comment]
Hey @RichardLuo0,

I see, so do you have a folder structure similar to the following all within a single repo? Where `src` contains your project and `package-1` and `package-2` are projects that you've cloned into your repo and amended their source:

```
.
|-- src/
|   |-- package.json
|
|-- vendor/
    |-- package-1/
    |   |-- package.json
    |
    |-- package-2/
        |-- package.json
```

If so, you should find that if you run `npm install ../vendor/package-1` from within `./src` then it will add `package-1` to the package.json of your project. This will have multiple benefits like allowing you to continue to import `package-1` like this:
```ts
import * as package1 from "package-1";
```
rather than:
```ts
import * as package1 from "../../vendor/package-1";
```
and it will mean that generate license file will be able to pick up on it too.

Please let me know if I've misunderstood your circumstance.

**Comment by RichardLuo0** [comment]
I see. Thank you for explaining.
