### ISSUE TITLE
Found multiple license files for zone.js@0.14.10

### ISSUE THREAD

**Issue by jayvdb** [TobyAndToby/generate-license-file#528]
**Describe the bug**

```
Found multiple license files for zone.js@0.14.10:
 - ./LICENSE.wrapped
 - ./LICENSE
```

LICENSE.wrapped is a generated file.  See https://www.npmjs.com/package/zone.js?activeTab=code

**How are you using generate-license-file?**
Library

**What version of generate-license-file are you using?**
3.5.1

**To Reproduce**

**Expected behavior**
`generate-license-file` detects that `LICENSE.wrapped` is useless.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tobysmith568** [comment]
Hey @jayvdb,

It's important to us that we uncover all possible license files for a dependency so that our consumers can make the most informed decision possible about their dependencies. We don't know why `zone.js` publishes with both `LICENSE` and `LICENSE.wrapped` but our preference is to pick up on all the possible options and let our consumers pick which one they want - rather than making that decision on their behalf.

As I think you've seen, Generate-License-File logs the following to the console:
```
Found multiple license files for zone.js@0.14.10:
 - ./license
 - ./LICENSE.wrapped
We suggest you determine which file you wish to use and replace the license content
for zone.js@0.14.10 using a generate-license-file config file.
See: https://generate-license-file.js.org/docs/cli/config-file for more information.
```

Using the `replace` option that we expose you can pick which of these files you'd like to use - which will also silence the warning.
