### ISSUE TITLE
License files not found for type-fest

### ISSUE THREAD

**Issue by jayvdb** [TobyAndToby/generate-license-file#530]
**Describe the bug**
https://github.com/sindresorhus/type-fest has two spdx identifiers and two license files, [`license-cc0`](https://github.com/sindresorhus/type-fest/blob/main/license-cc0) and [`license-mit`](https://github.com/sindresorhus/type-fest/blob/main/license-mit)

generate-license-file finds neither of them.

**How are you using generate-license-file?**
Library

**What version of generate-license-file are you using?**
3.5.1

**To Reproduce**

**Expected behavior**
The SPDX expression is shown, and both licenses are included.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tobysmith568** [comment]
Hey @jayvdb,

Generate-License-File would be able to find both of these license files, however the original author of `type-fest` [doesn't include either of them in the published package](https://www.npmjs.com/package/type-fest?activeTab=code).

When Generate-License-File cannot find a license file on disk it falls back to other locations and for `type-fest` it is able to find `"license": "(MIT OR CC0-1.0)"` in the package.json, so it uses that.

Because `"(MIT OR CC0-1.0)"` is a conditional SPDX license expression, you should find that Generate-License-File logs the following warning when you run it:
```
The license expression for type-fest@4.26.1 contains multiple licenses: "(MIT OR CC0-1.0)"
We suggest you determine which license applies to your project and replace the license content
for type-fest@4.26.1 using a generate-license-file config file.
See: https://generate-license-file.js.org/docs/cli/config-file for more information.
```

You can resolve this yourself by using one of the options that our methods expose like `replace` or `exclude` depending on which license you would like to use for `type-fest`. You can also reach out to the original author of `type-fest` and ask them to include their licenses in their published package.

**Comment by jayvdb** [comment]
Sorry I missed that, and thanks for pointing it out @tobysmith568 - I've raised https://github.com/sindresorhus/type-fest/issues/976 to fix this upstream
